### ISSUE TITLE
Pair: Remove redundant slippage check during providing liquidity

### ISSUE THREAD

**Issue by ueco-jb** [Phoenix-Protocol-Group/phoenix-contracts#93]
I realized that current implementation for providing liqudiity contains redundant slippage check.
At first we call:
https://github.com/Phoenix-Protocol-Group/phoenix-contracts/blob/9f1eca46828463707af215729eddddc5286b0cba/contracts/pair/src/contract.rs#L206-L214
which already checks if amounts are within 1% of current liquidity, to later assert it anyway:
https://github.com/Phoenix-Protocol-Group/phoenix-contracts/blob/9f1eca46828463707af215729eddddc5286b0cba/contracts/pair/src/contract.rs#L254-L260

1) Incorporate `custom_slippage_bps` parameter into `get_deposit_amounts` helper; compare that amount instead of hardcoded `Decimal::one`
2) After that, I think we can just remove the slippage assertion.

**Comment by gangov** [comment]
As per @ueco-jb's comments:

* Remove assert_slippage_tolerance usage in provide liquidity.
* Check if custom_slippage_bps is less then config.max_allowed_slippage() before, somewhere near the top of provide_liqudity
* Add new parameter allowed_slippage: Decimal to get_deposit_amounts
* Call get_deposit_amounts with Decimal::bps(custom_slippage) if provided, otherwise default for 1%
* Modify already working testcases and provide 1% slippage there
